export const experiences = [
  {
    id: 1,
    role: "Founder & CEO",
    company: "Emrift",
    companyUrl: "https://emrift.com",
    duration: "2024 — Present",
    location: "Patna, Bihar, India",
    type: "Full-time",
    summary: "Founded and built Emrift — a full-stack esports tournament management platform with Discord bot integration, web-based operations, payment systems, and scalable architecture.",
    highlights: [
      "Architected the entire full-stack platform using React, Node.js, Express, and MongoDB",
      "Designed and developed a Discord bot for automated tournament workflows and team management",
      "Integrated Razorpay for subscription and payment processing with secure backend flows",
      "Built admin dashboards, tournament CRUD systems, and dynamic event operations",
      "Implemented authentication, role-based access control, and real-time status updates",
      "Managed product strategy, system design, deployment, and iterative development end-to-end",
    ],
    tags: ["React", "Node.js", "MongoDB", "Discord.js", "Razorpay", "Product Architecture"],
  },
  {
    id: 2,
    role: "Full Stack Developer",
    company: "Independent / Freelance",
    companyUrl: "",
    duration: "2022 — 2024",
    location: "Remote",
    type: "Freelance",
    summary: "Built and delivered multiple full-stack web applications for clients and personal projects, focusing on MERN stack development, API design, and responsive UI engineering.",
    highlights: [
      "Developed custom web applications using React, Node.js, Express, and MongoDB",
      "Designed and implemented RESTful APIs with authentication, validation, and error handling",
      "Built responsive, accessible frontends with modern CSS frameworks and component architecture",
      "Handled end-to-end project delivery including database design, deployment, and post-launch support",
      "Worked with diverse clients to translate requirements into functional, production-grade products",
    ],
    tags: ["React", "Node.js", "Express", "MongoDB", "REST APIs", "Freelance"],
  },
];
