import { assets } from "../utils/allAssets";

export const projects = [
  {
    id: "emrift",
    title: "Emrift",
    tagline: "Esports Tournament Management Platform",
    type: "Flagship Startup",
    description: "A comprehensive esports tournament management platform that handles team creation, tournament registration, bracket management, Discord bot workflows, subscription billing, and admin operations — built as a scalable full-stack product from the ground up.",
    problem: "Esports tournament organizers rely on fragmented manual workflows — spreadsheets, Discord messages, and scattered payment tools — making it difficult to manage teams, brackets, and operations at scale.",
    solution: "Emrift centralizes the entire tournament lifecycle into one platform: team management, tournament CRUD, automated Discord workflows, Razorpay-powered payments, and an admin dashboard — all backed by a scalable MERN architecture.",
    outcome: "A production-grade platform handling end-to-end tournament operations, reducing manual overhead and providing a professional experience for organizers and participants.",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Mongoose", "Discord.js", "Razorpay", "JWT Auth", "Tailwind CSS"],
    liveLink: "https://emrift.vercel.app/",
    githubLink: "",
    caseStudyLink: "",
    featured: true,
    image: assets.projects.emrift,
    status: "Live",
  },
  {
    id: "portfolio-v2",
    title: "Portfolio Website",
    tagline: "Personal Developer Portfolio",
    type: "Personal Project",
    description: "A production-quality, data-driven portfolio website built with Vite, React, and Tailwind CSS. Designed to be easily customizable by editing only the database folder — a reusable template for any developer.",
    problem: "Most developer portfolios are either generic templates or overly complex to customize. There's a need for a clean, professional, data-driven portfolio that anyone can fork and make their own.",
    solution: "Built a fully component-based React application where all content lives in editable database files. Features dark mode, responsive design, smooth animations, and SEO optimization.",
    outcome: "A polished, recruiter-ready portfolio that communicates both technical depth and founder credibility, easily maintainable through structured data files.",
    techStack: ["React", "Vite", "Tailwind CSS", "Framer Motion", "React Router", "Lucide Icons"],
    liveLink: "https://sujeetcoder.github.io",
    githubLink: "https://github.com/sujeetcoder/sujeetcoder.github.io",
    caseStudyLink: "",
    featured: false,
    image: assets.projects.portfolio,
    status: "Live",
  },
];
